language: node_js
node_js:
    - 0.12
    - iojs

matrix:
  allow_failures:
    - node_js: 'iojs'

script:
  - npm run coverage && npm run report

notifications:
    email:
        on_success: never
        on_failure: change
